## Import Packages

In [1]:
import numpy as np
import matplotlib.pyplot as plt
import tensorflow as tf
import retro 

from skimage import transform 
from skimage.color import rgb2gray 

from collections import deque 

import random 
import warnings

warnings.filterwarnings('ignore')

/home/raed/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters


## Init Environment

In [2]:
env = retro.make(game='SpaceInvaders-Atari2600')

In [3]:
frame_size = env.observation_space 
num_actions = env.action_space.n

print ("Frame Size: \t", frame_size)
print("Action Size: \t", num_actions)

#one hot encoded actions matrix 
actions_1_hot = np.array(np.identity(num_actions, dtype=int).tolist())
print(actions_1_hot)

Frame Size: 	 Box(210, 160, 3)
Action Size: 	 8
[[1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1]]


## Preprocessing 

In [24]:
def preprocess_frame(frame):
    """
    Convert frames to grayscale, crop irrelevent parts, normalize pixels, 
    resize frame.
    
    Input is frame of size 210x160x3
    Returns frame of size 110x84x1 
    """
    grayed = rgb2gray(frame)
    cropped = grayed[8:-12, 4:-12]
    normed = cropped/255.0 
    resized = transform.resize(normed, [110,84])
    
    return resized #returns preprocessed frame 

stack_size = 4
def stack_frames(stacked_frames, frame, is_new_episode, stack_size=stack_size):
    """
    takes a frame/state and preprocesses it, 
    if same episode:
        adds to the stack state 
    else new episode: 
        creates stacked state 
    
    where the stacked state is 4 stacked states(frames)
    returns stacked state where axis=1 is for different frames 
    """
    frame = preprocess_frame(frame)
    if not is_new_episode:
        stacked_frames.append(frame)
        stacked_state = np.stack(stacked_frames, axis=2)
    
    else: 
        #init deque 
        stacked_frames = deque([np.zeros((110,84), dtype=np.int) 
                                for i in range(stack_size)], maxlen=4)
        #new episode so same frame x4 
        for i in range(4): stacked_frames.append(frame)
        
        stacked_state = np.stack(stacked_frames, axis=2)

    return stacked_state, stacked_frames
  

In [25]:
#init frame stack
stacked_frames  =  deque([np.zeros((110,84), dtype=np.int) for i in range(stack_size)], maxlen=4)
frame = np.zeros((110,84), dtype=np.int)

#test helper functions 
sample_state, stacked_frames = stack_frames(stacked_frames, frame, True)
print(np.shape(sample_state), np.shape(stacked_frames))

(110, 84, 4) (4, 110, 84)


## Hyper Params

In [6]:
#env params 
total_episodes = 50 #total num of episodes 
total_test_episodes = 10 #total num of episodes to test on 
max_steps = 50000 #max num of steps per episode 
bs = 64

#network params 
lr = 0.00025
state_size = [110,84,4]

#discount factor 
gamma = 0.9

#exploration params 
epsilon = 1.0 #starting value for eps greedy (explore)
max_eps = 1.0  #max value for eps greey 
min_eps = 0.01 #min value for eps greedy 
decay = 0.00001 #decay rate for eps 

#Recall Params
memory_size = 1000000
pretrained_len = bs #number of init memories 

training=False

## DQN: Model 


In [7]:
class DQN():
    def __init__(self, state_size, action_size, learning_rate, name='DQN', training=training):
        self.state_size = state_size
        self.action_size = action_size
        self.lr = learning_rate
        self.training = training
        with tf.variable_scope(name):
            #placeholders
            self.inputs = tf.placeholder(tf.float32,[None, *self.state_size])
            self.actions = tf.placeholder(tf.float32, [None, self.action_size])
            self.target_Q = tf.placeholder(tf.float32)
            
            #block 1 
            self.conv1 = tf.layers.conv2d(inputs=self.inputs, filters=32, 
                                          kernel_size=[8,8], 
                                          strides=(4,4), 
                                          padding='valid', 
                                          kernel_initializer= tf.contrib.layers.xavier_initializer_conv2d())
            self.bn1 = tf.layers.batch_normalization(self.conv1, epsilon=1e-5, training=self.training)
            self.elu1 = tf.nn.elu(self.bn1)
            
            #block 2
            self.conv2 = tf.layers.conv2d(inputs=self.elu1, filters=64, 
                                          kernel_size=[4,4], 
                                          strides=(2,2), 
                                          padding='valid', 
                                          kernel_initializer= tf.contrib.layers.xavier_initializer_conv2d())
            self.bn2 = tf.layers.batch_normalization(self.conv2, epsilon=1e-5, training=self.training)
            self.elu2 = tf.nn.elu(self.bn2)
            
            #block 3
            self.conv3 = tf.layers.conv2d(inputs=self.elu2, filters=128, 
                                          kernel_size=[4,4], 
                                          strides=(2,2), 
                                          padding='valid', 
                                          kernel_initializer= tf.contrib.layers.xavier_initializer_conv2d())
            self.bn3 = tf.layers.batch_normalization(self.conv3, epsilon=1e-5, training=self.training)
            self.elu3 = tf.nn.elu(self.bn3)
            
            #FC Block 
            self.flat = tf.layers.flatten(self.elu3)
            self.fc = tf.layers.dense(self.flat, units=512, activation=tf.nn.elu, 
                                       kernel_initializer=tf.contrib.layers.xavier_initializer())
            self.out = tf.layers.dense(self.fc, units=self.action_size, activation=None, 
                                       kernel_initializer=tf.contrib.layers.xavier_initializer())
            
            #Q-Value prediction 
            self.pred_Q = tf.reduce_sum(tf.multiply(self.out, self.actions), axis=1)
            
            #Loss Function 
            self.loss = tf.reduce_mean(tf.square(self.target_Q-self.pred_Q))
            
            #Optimizer 
            self.optim = tf.train.RMSPropOptimizer(learning_rate=self.lr).minimize(self.loss)
           

In [14]:
tf.reset_default_graph()

#init 
DQNetwork = DQN(state_size, num_actions, lr)

## Experience Replay

In [15]:
#memory class creates and manages deque 

class Memory():
    def __init__(self, mem_limit):
        self.cache = deque(maxlen=mem_limit)
    
    def add(self, exp):
        self.cache.append(exp)
    
    def sample(self, sample_size):
        sampling_ind = np.random.choice(np.arange(len(self.cache)), size=sample_size, replace=False)
        return [self.cache[i] for i in sampling_ind]

In [16]:
#init memory for first time 
memory = Memory(mem_limit=memory_size)

import pdb 

for i in range(pretrained_len):
    #pdb.set_trace()
    #initilize state for first step  
    if i == 0: 
        state = env.reset() #init state 
        state, stacked_frames = stack_frames(stacked_frames, state, True)
    
    #take a random action, record observations and add if not dead 
    choice = np.random.choice(np.arange(num_actions),size=1, replace=False)
    action = actions_1_hot[choice][0]    
    obs, reward, done, _ = env.step(action)
    
    #comment out if you want unseen 
    env.render()
    
    #stack new frame 
    next_state, stacked_frames = stack_frames(stacked_frames, obs, False)
    
    if not done:
        #add memory 
        memory.add((state, action, reward, next_state, done))
        #update state
        state = next_state
        
    else: #were dead
        #update next state 
        next_state = np.zeros_like(state)
        
        #add exp 
        memory.add((state, action, reward, next_state, done))

        #new episode and restart 
        env.reset()
        state, stacked_frames = stack_frames(stacked_frames, state, True)


## DQN: Training

In [17]:
#Function to predict action based on epsilon greedy 

def explore_exploit(epsilon, min_eps, decay_rate, decay_step, state, num_actions):
    #produce random number between 0 and 1 
    check = np.random.rand()
    explore_prob = min_eps + (epsilon-min_eps)*np.exp(-decay_rate*decay_step)
    
    #explore
    if explore_prob>check:
        #take random action 
        choice = random.randint(1,len(actions_1_hot))-1
        action = actions_1_hot[choice]  
        
    #exploit 
    else:
        #q vals predicted by network 
        Qs = sess.run(DQNetwork.out, feed_dict = {DQNetwork.inputs : state.reshape((1,*state.shape))})
        #choose action corresponding to best Q value 
        choice = np.argmax(Qs)
        action = actions_1_hot[choice]
    return action, explore_prob


In [18]:
#for saving 
saver = tf.train.Saver()
training = False 
episode_render = True 
decay_rate = decay

In [19]:
#training loop
if training == True: 
    with tf.Session() as sess:
        #init vars and decay rate
        sess.run(tf.global_variables_initializer())
        decay_step = 0 
        
        #rewards for each episode 
        episodic_rewards = [] 
        
        for episode in range(total_episodes):
            #init steps for episode 
            step = 0 
            
            #init observation
            state = env.reset()
            state, stacked_frame = stack_frames(stacked_frames, state, True)
            
            #list for rewards collected in episode 
            rewards_list = []
            
            while step < max_steps:
                ################SAMPLING#######################    
                #increments 
                step += 1
                decay_step += 1
                #if step % 50 == 0: print (step)
                #choose action 
                action, explore_prob = explore_exploit(epsilon, min_eps, decay_rate, decay_step, state, num_actions)

                #take action                 
                next_state, reward, done, _ = env.step(action)    
                env.render()
                
                rewards_list.append(reward) 
                
                #if were not dead 
                if not done:
                    #store transition after converting to proper format 
                    next_state, stacked_frames = stack_frames(stacked_frames, obs, False)

                    #add memory 
                    memory.add((state, action, reward, next_state, done))
                    #update state
                    state = next_state

                #if were dead     
                else: 
                    #update next state 
                    next_state = np.zeros_like(state)
                    next_state, stacked_frames = stack_frames(stacked_frames, next_state, False)
                    
                    #add episodic rewards 
                    tot_reward = np.sum(rewards_list)
                    episodic_rewards.append((episode, tot_reward))
                    
                    #print episode summary 
                    print(  'Episode: {}'.format(episode),
                            'Total reward: {}'.format(tot_reward),
                            'Explore P: {:.4f}'.format(explore_prob),
                            'Training Loss {:.4f}'.format(loss))
                    
                    #end episode 
                    step = max_steps
                    
                    #add exp 
                    memory.add((state, action, reward, next_state, done))
        
                ################Learning#######################    
                #extract minibatch values 
                mini_batch = memory.sample(bs)
                states_batch = [sample[0] for sample in mini_batch]
                actions_batch = [sample[1] for sample in mini_batch]
                rewards_batch = [sample[2] for sample in mini_batch]
                next_states_batch = [sample[3] for sample in mini_batch]
                dones_batch = [sample[4] for sample in mini_batch]
                
                #target qs to be set below 
                targ_qs_batch = []
                
                #get predicted Q's for each next state 
                next_qs_batch = sess.run(DQNetwork.out, feed_dict={DQNetwork.inputs : next_states_batch})
                
                #determine if state is terminal and set value for target_q
                for i in range(bs):
                    final_state = dones_batch[i]
                    
                    if final_state:
                        targ_qs_batch.append(rewards_batch[i])
                    
                    else:   
                        target_q = rewards_batch[i] + gamma * np.max(next_qs_batch[i])
                        targ_qs_batch.append(target_q)
                    
                
                #convert to np array 
                target_q = np.array([i for i in targ_qs_batch])
                
                #determine loss 
                loss, _ = sess.run([DQNetwork.loss, DQNetwork.optim], feed_dict={DQNetwork.inputs: states_batch,
                                                                               DQNetwork.target_Q: targ_qs_batch,
                                                                               DQNetwork.actions: actions_batch})
                
                
                #perform gradient update 
                
            if episode % 5 == 0:
                save_path = saver.save(sess, "./models/model_{}.ckpt".format(episode))
                print("Model Saved")              

In [29]:

test_episodes = 1 
saver = tf.train.Saver()

with tf.Session() as sess:

    #load the model 
    saver.restore(sess, "./models/model_40.ckpt")
    episodic_rewards = []

    #init state
    state = env.reset()
    state, stacked_frames = stack_frames(stacked_frames, state, True)
    
    #run for each episode  
    for episode in range(test_episodes):
        
        #reward list for single episodes 
        total_rewards = []

        #continue untill the agent dies 
        while True: 
            state = np.reshape(state, (1, *state.shape))
            q_preds = sess.run(DQNetwork.out, feed_dict={DQNetwork.inputs:state})
            choice = np.argmax(q_preds)
            action = actions_1_hot[choice]
            print(q_preds[0])
            #take action 
            new_state, reward, done, _ = env.step(action)
            env.render()

            total_rewards += [reward]
            
            if done:
                print ("""
                >>>>>>>>>>>>>>>>>>>> TESTING SUMMARY >>>>>>>>>>>>>>>>>>>>
                Reward: {}""".format(np.sum(total_rewards)))
                break 
            
            state, stacked_frames = stack_frames(stacked_frames, new_state, False)

    #env.close()

INFO:tensorflow:Restoring parameters from ./models/model_40.ckpt
[[4.457136  4.4597373 4.4845476 4.496893  4.491561  4.6021643 4.528149
  4.7433043]]
[[4.457111  4.4598904 4.4846115 4.496983  4.4915977 4.602172  4.528305
  4.7433834]]
[[4.4570794 4.460055  4.4846807 4.4970818 4.4916334 4.6021767 4.5284758
  4.7434664]]
[[4.4570537 4.4602118 4.484747  4.4971747 4.4916706 4.602183  4.5286384
  4.7435484]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.457045  4.460224  4.4847507 4.4971824 4.491668  4.6021776 4.52865
  4.7435513]]
[[4.4570727 4.4600596 4.484684  4.497083  4.4916325 4.6021724 4.528481
  4.7434673]]

[[4.4570794 4.460055  4.4846807 4.4970818 4.4916334 4.6021767 4.5284758
  4.7434664]]
[[4.4570537 4.4602118 4.484747  4.4971747 4.4916706 4.602183  4.5286384
  4.7435484]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.4570155 4.4603767 4.4848175 4.4972744 4.4917045 4.6021843 4.528808
  4.7436314]]
[[4.457045  4.460224  4.4847507 4.4971824 4.491668  4.6021776 4.52865
  4.7435513]]
[[4.4570727 4.4600596 4.484684  4.497083  4.4916325 4.6021724 4.528481
  4.7434673]]
[[4.457101  4.4599013 4.484616  4.4969907 4.491596  4.6021676 4.528317
  4.743387 ]]
[[4.457136  4.4597373 4.4845476 4.496893  4.491561  4.6021643 4.528149
  4.7433043]]
[[4.457136  4.4597373 4.4845476 4.496893  4.491561  4.6021643 4.

[[4.4125934 4.417226  4.4449344 4.4708667 4.4534197 4.55517   4.5009456
  4.704999 ]]
[[4.412662  4.417288  4.4449935 4.4709573 4.453474  4.5552382 4.500951
  4.7050705]]
[[4.4127297 4.4173393 4.4450507 4.4710326 4.4535213 4.555302  4.500948
  4.7051325]]
[[4.4127965 4.417406  4.4451113 4.4711437 4.4535623 4.5553656 4.5009327
  4.7052107]]
[[4.412858  4.41748   4.445173  4.4712596 4.4535995 4.5554247 4.5009212
  4.70529  ]]
[[4.412925  4.417572  4.4452405 4.471405  4.453644  4.555491  4.5009127
  4.705385 ]]
[[4.4129844 4.4176674 4.445307  4.4715505 4.4536796 4.5555477 4.5009055
  4.7054777]]
[[4.413029  4.4177213 4.4453464 4.4716516 4.4537015 4.5555854 4.500885
  4.7055387]]
[[4.412737  4.419492  4.4468246 4.4729595 4.45338   4.5548344 4.5030627
  4.7061405]]
[[4.4121466 4.4210014 4.4480295 4.4739394 4.4527164 4.553814  4.505028
  4.706457 ]]
[[4.411802  4.422579  4.449311  4.4750338 4.4522514 4.5529695 4.507058
  4.7069016]]
[[4.4111943 4.424114  4.450513  4.4759827 4.4516044 4.55190

[[4.3901887 4.43909   4.4577417 4.4733458 4.4378724 4.5416617 4.52041
  4.7068043]]
[[4.385714  4.439019  4.4569936 4.471333  4.4347486 4.5389085 4.519876
  4.7053757]]
[[4.3857503 4.4390254 4.457004  4.471351  4.4347568 4.5389304 4.5198817
  4.705386 ]]
[[4.3857536 4.439019  4.4570017 4.4713445 4.4347553 4.5389366 4.5198684
  4.705385 ]]
[[4.385938  4.439188  4.457169  4.471512  4.4348507 4.5390515 4.519982
  4.705537 ]]
[[4.3859534 4.439194  4.45718   4.4715185 4.4348516 4.53906   4.519979
  4.7055454]]
[[4.3861775 4.439437  4.457399  4.4717336 4.4349627 4.5391755 4.520165
  4.7057486]]
[[4.3861685 4.4394407 4.4574018 4.4717283 4.434952  4.539164  4.520167
  4.7057486]]
[[4.385984  4.4393635 4.457286  4.47161   4.4348493 4.539007  4.520163
  4.705641 ]]
[[4.385974  4.43937   4.4572897 4.471613  4.434843  4.538996  4.520168
  4.7056417]]
[[4.3859344 4.439334  4.4572525 4.471595  4.4348326 4.5389733 4.520163
  4.7056065]]
[[4.3859353 4.4393306 4.4572554 4.471597  4.434831  4.5389743 4.

[[4.4116936 4.467836  4.4853683 4.48497   4.457993  4.569019  4.535711
  4.731763 ]]
[[4.411693  4.4678264 4.4853587 4.484978  4.4579887 4.5690084 4.535705
  4.7317553]]
[[4.411693  4.4678326 4.485358  4.4849825 4.45799   4.569008  4.5357084
  4.731756 ]]
[[4.4117227 4.467849  4.4853787 4.4850225 4.458007  4.569019  4.535724
  4.7317734]]
[[4.4117255 4.4678545 4.4853816 4.485029  4.45801   4.569019  4.535729
  4.7317753]]
[[4.414697  4.4692    4.487111  4.4862785 4.4603953 4.572269  4.536142
  4.733466 ]]
[[4.417803  4.470582  4.4889174 4.487627  4.4629436 4.575668  4.536557
  4.7352505]]
[[4.420706  4.471901  4.490647  4.488854  4.4653316 4.5789075 4.536921
  4.736952 ]]
[[4.423945  4.473386  4.4925203 4.4901843 4.4679427 4.582481  4.5372944
  4.7388353]]
[[4.4238944 4.473334  4.492483  4.4901023 4.4679036 4.58246   4.5372467
  4.738796 ]]
[[4.4239016 4.473338  4.4924836 4.4901133 4.4679055 4.582459  4.53725
  4.7388   ]]
[[4.423859  4.4732995 4.492453  4.4900594 4.467874  4.58244   4

[[4.424918  4.4447527 4.472042  4.476825  4.465651  4.577179  4.510134
  4.7265863]]
[[4.4249988 4.444808  4.4721117 4.4769197 4.465698  4.5772157 4.5101776
  4.7266436]]
[[4.4249988 4.4448066 4.472113  4.47691   4.4656987 4.5772195 4.510177
  4.7266445]]
[[4.4249816 4.4448037 4.4721165 4.4768806 4.4656944 4.577226  4.510171
  4.7266426]]
[[4.4249797 4.444802  4.4721165 4.47687   4.465693  4.577228  4.5101705
  4.7266426]]
[[4.4249797 4.444808  4.472133  4.476851  4.4657044 4.5772424 4.510179
  4.726655 ]]
[[4.4249873 4.4448075 4.4721327 4.476863  4.4657044 4.577241  4.5101743
  4.726656 ]]
[[4.4249926 4.4448123 4.472139  4.476864  4.4657116 4.577247  4.51018
  4.72666  ]]
[[4.424982  4.4448047 4.4721293 4.4768605 4.465703  4.5772405 4.510169
  4.726652 ]]
[[4.424948  4.4447775 4.472096  4.4768243 4.46568   4.5772204 4.510147
  4.7266235]]
[[4.4249363 4.44477   4.4720907 4.4768    4.465678  4.5772204 4.5101438
  4.726619 ]]
[[4.424948  4.444788  4.4721127 4.476808  4.465697  4.5772376 

[[4.425054  4.4448624 4.472241  4.4769015 4.4657845 4.5773077 4.5102277
  4.7267323]]
[[4.4250607 4.444865  4.472242  4.476917  4.465787  4.5773067 4.5102305
  4.726734 ]]
[[4.425055  4.4448667 4.4722447 4.4769044 4.465788  4.57731   4.5102324
  4.726735 ]]
[[4.425052  4.4448676 4.472246  4.476895  4.4657893 4.577312  4.510235
  4.726736 ]]
[[4.4250464 4.4448643 4.4722457 4.476882  4.465789  4.577313  4.5102334
  4.726735 ]]
[[4.4250417 4.4448633 4.4722447 4.476869  4.4657884 4.5773125 4.510234
  4.726733 ]]
[[4.4250417 4.4448605 4.472243  4.476879  4.4657845 4.5773096 4.510228
  4.7267313]]
[[4.4250464 4.4448614 4.4722404 4.476889  4.4657836 4.577307  4.5102277
  4.7267303]]
[[4.425054  4.4448624 4.472241  4.4769015 4.4657845 4.5773077 4.5102277
  4.7267323]]
[[4.4250607 4.444865  4.472242  4.476917  4.465787  4.5773067 4.5102305
  4.726734 ]]
[[4.425055  4.4448667 4.4722447 4.4769044 4.465788  4.57731   4.5102324
  4.726735 ]]
[[4.425052  4.4448676 4.472246  4.476895  4.4657893 4.577

[[4.4342065 4.4388885 4.4675107 4.478767  4.4725647 4.5829897 4.5086846
  4.7261066]]
[[4.434135  4.4389744 4.4675775 4.4787927 4.4725857 4.582966  4.508787
  4.7261534]]
[[4.4342146 4.4389095 4.467563  4.478768  4.472595  4.583006  4.50872
  4.7261333]]
[[4.4342237 4.438909  4.467592  4.47877   4.4726143 4.5830083 4.50873
  4.7261477]]
[[4.434343  4.4388256 4.4675794 4.478745  4.47264   4.583076  4.5086346
  4.7261286]]
[[4.4344583 4.4388094 4.4676223 4.47877   4.472703  4.5831504 4.50862
  4.726158 ]]
[[4.434572  4.4387283 4.467615  4.4787445 4.4727287 4.583221  4.508525
  4.726142 ]]
[[4.4346824 4.438707  4.467655  4.478764  4.4727855 4.5832906 4.508505
  4.7261696]]
[[4.434739  4.4386554 4.4676533 4.47874   4.4727983 4.58333   4.5084505
  4.726156 ]]
[[4.4348693 4.438665  4.4677105 4.4787993 4.472879  4.583409  4.5084686
  4.726207 ]]
[[4.4348693 4.438672  4.4677114 4.478797  4.472879  4.5834093 4.5084796
  4.726207 ]]
[[4.4348793 4.438689  4.467716  4.4788094 4.4728985 4.583414  4

[[4.418159  4.422375  4.4524336 4.471174  4.4591265 4.563275  4.5024924
  4.7108593]]
[[4.418097  4.42231   4.4523845 4.4710755 4.4590874 4.563235  4.5024657
  4.710801 ]]
[[4.4145947 4.4208145 4.450102  4.469436  4.4560637 4.5603104 4.5013866
  4.708436 ]]
[[4.411037  4.419501  4.447903  4.4678435 4.4530425 4.5573726 4.5005355
  4.7061234]]
[[4.407324  4.4178767 4.4454956 4.466077  4.4499097 4.5542774 4.4994817
  4.7036037]]
[[4.403703  4.416317  4.4431376 4.464392  4.4468265 4.5512233 4.498437
  4.7011633]]
[[4.4031334 4.41582   4.442669  4.4638305 4.4464364 4.550776  4.498145
  4.700697 ]]
[[4.402962  4.4156485 4.442533  4.4636188 4.4462957 4.5506587 4.498004
  4.700548 ]]
[[4.4023795 4.4151397 4.442036  4.463057  4.445936  4.550199  4.4977636
  4.7000656]]
[[4.402263  4.415029  4.4419327 4.4629073 4.445861  4.550122  4.4976974
  4.6999617]]
[[4.4019995 4.4147677 4.441667  4.4626036 4.4456925 4.5498953 4.4975896
  4.699709 ]]
[[4.401895  4.414647  4.4415584 4.4624643 4.445626  4.549

[[4.3982134 4.4473324 4.46458   4.475995  4.444187  4.5523615 4.5258565
  4.71257  ]]
[[4.3982673 4.447359  4.464603  4.4760213 4.4442163 4.5523987 4.5258746
  4.712598 ]]
[[4.3982573 4.4473596 4.464604  4.476014  4.4442105 4.5523973 4.5258713
  4.712595 ]]
[[4.3982463 4.4473705 4.464593  4.476015  4.444212  4.552382  4.5258994
  4.712596 ]]
[[4.3982105 4.4473605 4.46458   4.4759936 4.444193  4.5523577 4.5258946
  4.712579 ]]
[[4.3979964 4.4473248 4.46449   4.4759007 4.4440975 4.552199  4.5259376
  4.712492 ]]
[[4.397965  4.447321  4.464483  4.475883  4.4440804 4.552177  4.5259356
  4.7124805]]
[[4.3979115 4.4473033 4.4644356 4.4758554 4.4440503 4.5521226 4.5259485
  4.71245  ]]
[[4.3979297 4.4473124 4.464444  4.4758625 4.44406   4.5521345 4.525958
  4.7124586]]
[[4.397969  4.4473    4.464429  4.4758577 4.444057  4.55216   4.5259295
  4.712455 ]]
[[4.3979716 4.447273  4.464413  4.4758353 4.4440374 4.552163  4.525891
  4.7124376]]
[[4.398171  4.447301  4.4644704 4.4759097 4.444108  4.55

[[4.387517  4.4453964 4.463592  4.4664283 4.4343195 4.5473886 4.5146537
  4.710951 ]]
[[4.3874774 4.4453125 4.463515  4.4663815 4.434304  4.547328  4.5146337
  4.7108917]]
[[4.387481  4.44532   4.463522  4.466381  4.4343057 4.547338  4.5146327
  4.7108974]]
[[4.387485  4.445285  4.4634886 4.4663663 4.434308  4.547315  4.514629
  4.7108765]]
[[4.3874917 4.4452972 4.463499  4.4663644 4.4343085 4.5473275 4.5146265
  4.710884 ]]
[[4.387552 4.445346 4.463537 4.466427 4.434376 4.547368 4.514695 4.710929]]
[[4.3875446 4.445343  4.463532  4.4664173 4.434364  4.5473647 4.514686
  4.710924 ]]
[[4.387587  4.445373  4.4635496 4.466457  4.4344125 4.547384  4.514742
  4.710949 ]]
[[4.3875604 4.4453545 4.463526  4.4664326 4.434394  4.5473657 4.5147314
  4.710928 ]]
[[4.3876405 4.4454203 4.4635787 4.4665084 4.434464  4.5474124 4.514809
  4.710987 ]]
[[4.387629  4.4454184 4.46357   4.4664974 4.4344544 4.547406  4.514804
  4.7109785]]
[[4.387691  4.445472  4.46361   4.4665475 4.434507  4.5474496 4.51485

[[4.402452  4.459384  4.474582  4.4773946 4.4484224 4.5627866 4.527943
  4.722431 ]]
[[4.4021435 4.459676  4.474737  4.477475  4.4484506 4.562635  4.5283136
  4.722556 ]]
[[4.4021583 4.4597034 4.4747605 4.477499  4.4484725 4.5626507 4.5283437
  4.722577 ]]
[[4.40216   4.4596763 4.4747396 4.4774837 4.4484625 4.5626407 4.5283165
  4.7225657]]
[[4.402174  4.4597163 4.4747677 4.477513  4.4484935 4.56266   4.528361
  4.722596 ]]
[[4.402384  4.459574  4.474691  4.4774876 4.448499  4.562758  4.528173
  4.7225504]]
[[4.402379  4.459625  4.474725  4.4775195 4.4485254 4.5627627 4.528234
  4.722583 ]]
[[4.402388  4.459587  4.4746914 4.4775004 4.448508  4.5627484 4.528188
  4.7225637]]
[[4.4023833 4.459638  4.474725  4.4775295 4.448532  4.5627494 4.52825
  4.7225933]]
[[4.4023137 4.4596543 4.474712  4.47752   4.4485054 4.5626993 4.528276
  4.7225866]]
[[4.4023013 4.4597197 4.4747543 4.4775586 4.4485364 4.5627017 4.528353
  4.722625 ]]
[[4.402268  4.4597387 4.474748  4.477555  4.4485273 4.562678  4

[[4.3875613 4.454805  4.4669724 4.4735894 4.4385314 4.548452  4.5305176
  4.7131004]]
[[4.3875666 4.4548106 4.4669766 4.473596  4.438539  4.5484548 4.5305247
  4.713105 ]]
[[4.387572  4.454815  4.4669814 4.4736    4.438542  4.5484595 4.5305276
  4.71311  ]]
[[4.3875933 4.454834  4.4670014 4.4736257 4.4385595 4.5484734 4.530546
  4.713127 ]]
[[4.3875976 4.4548373 4.467006  4.473627  4.4385614 4.5484767 4.5305476
  4.713131 ]]
[[4.387609  4.4548492 4.4670167 4.473644  4.438574  4.5484815 4.5305595
  4.7131395]]
[[4.387608  4.454851  4.4670186 4.473643  4.4385743 4.5484834 4.530561
  4.7131414]]
[[4.3876014 4.4548397 4.4670086 4.473638  4.438567  4.548474  4.530553
  4.713131 ]]
[[4.3876014 4.4548445 4.467011  4.473639  4.438569  4.5484767 4.5305552
  4.713134 ]]
[[4.3875947 4.454835  4.4670014 4.473634  4.438562  4.5484686 4.5305476
  4.713126 ]]
[[4.3876033 4.4548426 4.46701   4.473644  4.4385676 4.548473  4.530554
  4.713133 ]]
[[4.3875847 4.4548273 4.466992  4.4736276 4.438553  4.5484

[[4.3922224 4.4196887 4.442011  4.465357  4.438845  4.5421968 4.506644
  4.696416 ]]
[[4.3922787 4.4197216 4.442049  4.465401  4.438897  4.5422354 4.5066724
  4.696454 ]]
[[4.392355  4.4197803 4.4421253 4.4654818 4.438956  4.542291  4.506718
  4.696518 ]]
[[4.3922    4.419628  4.441968  4.4653263 4.4388394 4.542168  4.5065856
  4.696377 ]]
[[4.392296  4.4197083 4.44206   4.465428  4.438916  4.542235  4.5066547
  4.696458 ]]
[[4.392145  4.4195642 4.4419065 4.4652877 4.4387946 4.5421157 4.5065246
  4.6963196]]
[[4.392239  4.419648  4.442001  4.4653926 4.438872  4.5421853 4.5065928
  4.6964016]]
[[4.39214   4.4195633 4.441904  4.4653187 4.4387865 4.5420938 4.5065255
  4.69631  ]]
[[4.3922086 4.419631  4.441979  4.4653993 4.438844  4.5421443 4.5065827
  4.696373 ]]
[[4.3920865 4.4195337 4.4418707 4.4653015 4.4387527 4.542043  4.5065107
  4.696271 ]]
[[4.3921514 4.419594  4.441935  4.465376  4.4388065 4.5420837 4.5065656
  4.696327 ]]
[[4.39195   4.419423  4.4417467 4.465169  4.438656  4.54

[[4.4293456 4.429966  4.456602  4.4755473 4.469688  4.5783987 4.508118
  4.7174606]]
[[4.429341  4.429961  4.456594  4.4755387 4.469689  4.578393  4.5081215
  4.717454 ]]
[[4.4293714 4.429986  4.4566345 4.4755645 4.4697027 4.578426  4.5081215
  4.7174854]]
[[4.4293666 4.4299827 4.4566298 4.475557  4.4697013 4.578421  4.5081277
  4.7174807]]
[[4.4293504 4.429964  4.4566216 4.4755344 4.469683  4.578413  4.5081034
  4.7174664]]
[[4.4293447 4.429955  4.4566126 4.475521  4.46968   4.578406  4.5081058
  4.717457 ]]
[[4.4293137 4.429911  4.4565783 4.475465  4.469654  4.578376  4.5080905
  4.7174187]]
[[4.4293075 4.429908  4.456574  4.4754596 4.4696517 4.5783706 4.5080943
  4.717413 ]]
[[4.4293323 4.429921  4.456594  4.4754796 4.469662  4.578385  4.508098
  4.717429 ]]
[[4.4293284 4.429922  4.4565916 4.4754777 4.4696636 4.5783834 4.5081053
  4.7174273]]
[[4.429339  4.429934  4.4566045 4.4754987 4.4696646 4.5783944 4.5080953
  4.7174406]]
[[4.429341  4.429939  4.4566054 4.4755006 4.4696674 4.57

[[4.416716  4.446682  4.4718213 4.477526  4.4618464 4.573993  4.5149484
  4.7238865]]
[[4.4167137 4.4466805 4.471813  4.477525  4.461844  4.5739956 4.5149527
  4.72388  ]]
[[4.4167266 4.4466553 4.471805  4.477513  4.4618387 4.5739994 4.514918
  4.7238693]]
[[4.4167104 4.446669  4.4718037 4.47752   4.4618373 4.573995  4.5149426
  4.7238684]]
[[4.416726  4.4466496 4.4717994 4.477511  4.461838  4.5740027 4.5149155
  4.7238636]]
[[4.416703  4.4466457 4.47179   4.4775004 4.4618273 4.573991  4.514918
  4.723851 ]]
[[4.416717  4.446625  4.4717846 4.47749   4.4618263 4.5739956 4.5148926
  4.7238464]]
[[4.4167094 4.4466166 4.4717755 4.4774823 4.461819  4.573988  4.514888
  4.723838 ]]
[[4.4167075 4.4466076 4.471772  4.477475  4.4618154 4.5739856 4.514875
  4.723833 ]]
[[4.4167094 4.446603  4.47177   4.477475  4.461812  4.5739822 4.514876
  4.72383  ]]
[[4.4167    4.446603  4.4717674 4.477472  4.46181   4.57398   4.514874
  4.7238283]]
[[4.416721  4.4465933 4.471768  4.4774723 4.461812  4.573988

[[4.4171977 4.4745655 4.4921765 4.4887266 4.4636726 4.5779524 4.53861
  4.737277 ]]
[[4.4171977 4.474604  4.492194  4.488751  4.4636827 4.577964  4.538649
  4.737296 ]]
[[4.4172635 4.4744644 4.492147  4.488671  4.463666  4.577995  4.538506
  4.7372313]]
[[4.4172606 4.4744997 4.492163  4.488691  4.4636745 4.578002  4.5385423
  4.7372494]]
[[4.417353  4.474309  4.4920993 4.4885902 4.4636483 4.578024  4.5383544
  4.7371597]]
[[4.417349  4.474345  4.4921155 4.4886117 4.463656  4.5780296 4.538392
  4.737176 ]]
[[4.41737   4.474247  4.492072  4.4885488 4.4636345 4.57803   4.5382953
  4.7371254]]
[[4.4173646 4.474283  4.492086  4.4885674 4.463641  4.5780416 4.5383286
  4.7371416]]
[[4.417372  4.4742155 4.4920526 4.4885144 4.4636245 4.578044  4.538259
  4.7371025]]
[[4.417375  4.4742427 4.4920654 4.4885306 4.463631  4.5780597 4.538287
  4.737116 ]]
[[4.417608  4.4742565 4.492118  4.4886217 4.4637485 4.578213  4.5382833
  4.737179 ]]
[[4.4176087 4.474306  4.492152  4.4886613 4.4637766 4.5782213

[[4.387568  4.4408574 4.4575033 4.471424  4.4366007 4.540912  4.521054
  4.70681  ]]
[[4.3875823 4.440882  4.4575105 4.47145   4.436614  4.5409474 4.521068
  4.7068233]]
[[4.3875957 4.4409027 4.457514  4.471463  4.436631  4.5409827 4.52108
  4.706834 ]]
[[4.3876166 4.4409275 4.45752   4.471492  4.4366465 4.541019  4.521096
  4.706848 ]]
[[4.3877044 4.4410076 4.457582  4.4715896 4.4366875 4.541091  4.5211453
  4.7069187]]
[[4.38767   4.440993  4.4575768 4.4715314 4.4366784 4.5410953 4.5211377
  4.706909 ]]
[[4.38764   4.4409914 4.4576035 4.4714355 4.436671  4.5411243 4.52114
  4.7069263]]
[[4.3876247 4.4409914 4.457616  4.471391  4.4366765 4.541144  4.5211473
  4.706934 ]]
[[4.387547  4.4409456 4.4576077 4.471246  4.4366517 4.5411534 4.5211163
  4.7069063]]
[[4.3875775 4.4409676 4.4576273 4.4712753 4.4366665 4.541168  4.5211377
  4.7069283]]
[[4.3876586 4.441032  4.4576964 4.4713902 4.4367013 4.5412216 4.5211744
  4.706992 ]]
[[4.387676  4.441046  4.4577055 4.4714103 4.436711  4.5412326

[[4.397035  4.4188685 4.443104  4.468306  4.44222   4.543124  4.5070014
  4.6982603]]
[[4.39708   4.418912  4.443136  4.468367  4.442249  4.5431657 4.507026
  4.6982956]]
[[4.397092  4.418926  4.4431434 4.468381  4.4422593 4.5431905 4.50703
  4.698305 ]]
[[4.397125  4.4189568 4.443164  4.4684215 4.44228   4.5432267 4.5070434
  4.698329 ]]
[[4.397141  4.418982  4.4431806 4.4684415 4.44229   4.5432663 4.5070443
  4.698346 ]]
[[4.397263  4.419008  4.4432144 4.4685087 4.442357  4.54337   4.507047
  4.698393 ]]
[[4.3972793 4.4190283 4.4432297 4.4685273 4.4423704 4.5434117 4.5070443
  4.698408 ]]
[[4.397389  4.4190803 4.4432755 4.4686074 4.4424443 4.543511  4.5070786
  4.6984673]]
[[4.3973994 4.419093  4.443289  4.468622  4.442457  4.5435224 4.507092
  4.6984787]]
[[4.397326  4.4191413 4.443306  4.4686217 4.442451  4.5434804 4.5071535
  4.698491 ]]
[[4.397333  4.4191465 4.443313  4.468629  4.4424605 4.5434833 4.5071673
  4.6984987]]
[[4.3972297 4.419167  4.44331   4.4686017 4.442426  4.54342

[[4.4327574 4.4379935 4.4639335 4.479823  4.472695  4.581714  4.51407
  4.7230644]]
[[4.4327583 4.4380198 4.463932  4.4798336 4.4726954 4.5817323 4.514069
  4.7230654]]
[[4.4351726 4.4423137 4.467753  4.4824147 4.4752374 4.584958  4.5175114
  4.72608  ]]
[[4.4379277 4.447085  4.472048  4.485391  4.478181  4.588503  4.521375
  4.7295094]]
[[4.440286  4.451583  4.476032  4.4881115 4.480783  4.59173   4.5250363
  4.732645 ]]
[[4.4430165 4.4562697 4.4802017 4.4909763 4.4836526 4.59529   4.528793
  4.7360086]]
[[4.4428973 4.4561715 4.4800982 4.4908366 4.4835734 4.5952086 4.528731
  4.735903 ]]
[[4.4429073 4.456186  4.480099  4.490841  4.483584  4.5952177 4.528747
  4.7359056]]
[[4.442891  4.4561834 4.4801    4.4908175 4.483567  4.5952325 4.5287232
  4.735899 ]]
[[4.442903  4.4562054 4.480103  4.490832  4.4835777 4.5952435 4.528741
  4.7359047]]
[[4.4429946 4.4563036 4.4802017 4.49093   4.483628  4.5953407 4.528769
  4.7359924]]
[[4.443     4.456335  4.480212  4.4909472 4.4836335 4.5953593 4

[[4.430574  4.4343195 4.4597077 4.480483  4.4707694 4.5787034 4.5136213
  4.720394 ]]
[[4.426699  4.428481  4.454508  4.476755  4.4666815 4.5733957 4.5097456
  4.715663 ]]
[[4.422788  4.4227147 4.4494104 4.4730706 4.462668  4.5681667 4.505952
  4.7109995]]
[[4.4185905 4.4164457 4.4438353 4.468981  4.458318  4.562574  4.50178
  4.70595  ]]
[[4.4185996 4.416422  4.4438324 4.4689674 4.4583187 4.5625834 4.501749
  4.705946 ]]
[[4.4186254 4.4164286 4.443839  4.468982  4.4583316 4.5625963 4.501752
  4.7059593]]
[[4.4186063 4.416418  4.443834  4.468971  4.4583297 4.5625887 4.5017567
  4.70595  ]]
[[4.41863   4.4164248 4.443839  4.468983  4.458342  4.5625997 4.501761
  4.7059603]]
[[4.418591  4.4164314 4.443837  4.468976  4.458343  4.5625815 4.5017934
  4.705949 ]]
[[4.418599  4.4164457 4.4438453 4.468986  4.458345  4.5625896 4.501799
  4.7059584]]
[[4.418526  4.416462  4.443837  4.4689684 4.4583225 4.5625534 4.50183
  4.7059374]]
[[4.418529  4.416482  4.443847  4.4689765 4.458319  4.562563  4

[[4.4004817 4.4290786 4.44697   4.4746737 4.4465113 4.550141  4.5184836
  4.7026625]]
[[4.4004865 4.429082  4.4469767 4.474677  4.446515  4.5501456 4.5184865
  4.702667 ]]
[[4.3999906 4.4312906 4.448991  4.4754615 4.446359  4.549792  4.5193977
  4.7042017]]
[[4.3994937 4.433873  4.4512954 4.476462  4.446222  4.549502  4.5205665
  4.7059345]]
[[4.3992305 4.4362974 4.4534845 4.4774704 4.446236  4.549275  4.521644
  4.7076645]]
[[4.398865 4.438988 4.455891 4.478585 4.446258 4.549071 4.52292  4.709524]]
[[4.3988376 4.4389663 4.4558673 4.4785533 4.446239  4.5490556 4.5229
  4.709502 ]]
[[4.3988137 4.438936  4.455847  4.4785223 4.4462132 4.5490394 4.522869
  4.709483 ]]
[[4.3987584 4.4388757 4.455794  4.478449  4.446177  4.549004  4.5228276
  4.7094336]]
[[4.398727  4.438842  4.4557705 4.478408  4.4461503 4.548987  4.5227923
  4.7094097]]
[[4.3987155 4.438816  4.455749  4.478384  4.4461412 4.5489745 4.522779
  4.7093916]]
[[4.3986926 4.4388003 4.4557343 4.478358  4.446129  4.5489635 4.522766

[[4.3838124 4.4592667 4.4714355 4.4794035 4.4398828 4.5482106 4.5324483
  4.717559 ]]
[[4.3838186 4.4592633 4.471432  4.47941   4.439884  4.548207  4.5324483
  4.717559 ]]
[[4.3838787 4.4593153 4.4714875 4.47948   4.4399176 4.548243  4.5324807
  4.7176065]]
[[4.3838687 4.4593053 4.471477  4.479474  4.4399114 4.548233  4.532476
  4.717598 ]]
[[4.383923  4.4593487 4.471526  4.4795384 4.43994   4.5482674 4.532499
  4.717641 ]]
[[4.383926  4.4593544 4.4715285 4.479546  4.4399433 4.5482674 4.5325055
  4.7176437]]
[[4.3839073 4.459346  4.471518  4.4795265 4.4399366 4.5482607 4.532498
  4.717634 ]]
[[4.3839264 4.459362  4.4715314 4.4795456 4.4399514 4.54827   4.5325155
  4.7176485]]
[[4.3839135 4.45936   4.471528  4.4795327 4.439955  4.5482683 4.532521
  4.7176456]]
[[4.3839364 4.459381  4.471545  4.4795628 4.4399714 4.5482807 4.532541
  4.717662 ]]
[[4.383871  4.4593368 4.4714966 4.479482  4.439936  4.5482497 4.532506
  4.717619 ]]
[[4.383904  4.459367  4.471521  4.479525  4.4399605 4.548269

[[4.421843  4.4760156 4.493793  4.4930396 4.468441  4.5836473 4.5364833
  4.7415104]]
[[4.421845  4.476019  4.4937963 4.493038  4.4684434 4.583648  4.5364866
  4.7415133]]
[[4.42184   4.4760094 4.4937882 4.4930353 4.468437  4.5836415 4.5364776
  4.7415056]]
[[4.4218154 4.475995  4.493777  4.492997  4.4684243 4.583636  4.536466
  4.7414923]]
[[4.4218116 4.4759893 4.493772  4.492995  4.468418  4.5836315 4.5364585
  4.7414875]]
[[4.421794  4.475977  4.4937615 4.492961  4.4684076 4.583627  4.53645
  4.741476 ]]
[[4.421783  4.475965  4.49375   4.492949  4.4683967 4.5836196 4.5364375
  4.7414665]]
[[4.4217887 4.475973  4.4937596 4.492955  4.4684043 4.5836253 4.536446
  4.741474 ]]
[[4.421773  4.4759583 4.4937468 4.492933  4.4683914 4.583618  4.536432
  4.7414618]]
[[4.421721  4.4759154 4.4936843 4.4928894 4.4683485 4.583575  4.536402
  4.741413 ]]
[[4.4216866 4.475889  4.493659  4.492846  4.468327  4.5835614 4.5363774
  4.741391 ]]
[[4.421661  4.4758654 4.493611  4.492847  4.4682984 4.583524

[[4.42174   4.4758887 4.4937325 4.492872  4.468352  4.5835934 4.536365
  4.741433 ]]
[[4.421751  4.475893  4.493735  4.4928875 4.4683547 4.583594  4.536368
  4.741437 ]]
[[4.421743  4.475893  4.4937363 4.492875  4.4683557 4.5835958 4.53637
  4.741438 ]]
[[4.4217377 4.475893  4.4937377 4.492866  4.468357  4.5835986 4.536371
  4.741436 ]]
[[4.421733  4.475892  4.4937367 4.492852  4.468356  4.5835986 4.5363703
  4.741435 ]]
[[4.4217286 4.4758883 4.493735  4.4928365 4.4683547 4.5835986 4.53637
  4.741432 ]]
[[4.4217315 4.4758883 4.4937334 4.492849  4.468353  4.5835958 4.536367
  4.741432 ]]
[[4.4217324 4.475888  4.4937315 4.4928617 4.468352  4.583593  4.536366
  4.741432 ]]
[[4.42174   4.4758887 4.4937325 4.492872  4.468352  4.5835934 4.536365
  4.741433 ]]
[[4.421751  4.475893  4.493735  4.4928875 4.4683547 4.583594  4.536368
  4.741437 ]]
[[4.421743  4.475893  4.4937363 4.492875  4.4683557 4.5835958 4.53637
  4.741438 ]]
[[4.4217377 4.475893  4.4937377 4.492866  4.468357  4.5835986 4.536

[[4.417215  4.4574275 4.4790163 4.481195  4.4644647 4.577855  4.5215974
  4.7312155]]
[[4.4173217 4.4574018 4.4790487 4.4812145 4.46451   4.5779305 4.5215535
  4.7312365]]
[[4.417422  4.457365  4.479056  4.481213  4.464554  4.577988  4.5215254
  4.731242 ]]
[[4.417454  4.4574003 4.4790916 4.481255  4.464581  4.578015  4.521553
  4.7312756]]
[[4.4173627 4.4573402 4.479023  4.4811625 4.464525  4.577954  4.5215216
  4.731203 ]]
[[4.4173465 4.4573927 4.479047  4.4811954 4.4645357 4.577945  4.5215783
  4.73123  ]]
[[4.4172206 4.457358  4.478978  4.4811234 4.464468  4.577859  4.5215716
  4.731165 ]]
[[4.417189  4.4573936 4.4789934 4.4811263 4.464472  4.5778537 4.5216174
  4.7311754]]
[[4.4171443 4.457433  4.478981  4.4811654 4.4644628 4.577811  4.5216618
  4.7311745]]
[[4.4170976 4.457458  4.4789815 4.4811473 4.4644575 4.577794  4.521703
  4.7311716]]
[[4.4171033 4.4575396 4.479005  4.4812436 4.4644794 4.577787  4.521774
  4.731208 ]]
[[4.417049  4.4575624 4.479     4.4812274 4.464465  4.577

[[4.4394526 4.4306154 4.4587326 4.478623  4.4760156 4.587019  4.5066047
  4.7216244]]
[[4.439471  4.4306145 4.4587483 4.4786153 4.4760323 4.587028  4.5066266
  4.721627 ]]
[[4.4392366 4.43039   4.4585247 4.4783225 4.4758873 4.586822  4.506554
  4.7214003]]
[[4.439263  4.430416  4.458554  4.4783497 4.475913  4.586843  4.506576
  4.721427 ]]
[[4.4390483 4.4302135 4.4583435 4.4780974 4.4757824 4.586657  4.5064936
  4.7212276]]
[[4.439084  4.430254  4.4583755 4.4781494 4.4758143 4.586683  4.506519
  4.721265 ]]
[[4.4390597 4.4302363 4.458366  4.4781356 4.475795  4.5866756 4.506482
  4.7212563]]
[[4.4391456 4.4303403 4.458446  4.4782815 4.4758673 4.58674   4.5065365
  4.7213497]]
[[4.4391456 4.4303656 4.458464  4.4783263 4.4758615 4.5867496 4.506518
  4.7213726]]
[[4.439282  4.4305167 4.4585905 4.4785404 4.475972  4.586848  4.506602
  4.72151  ]]
[[4.4393573 4.430627  4.458681  4.4787097 4.47602   4.586905  4.5066347
  4.7216053]]
[[4.439487  4.4307785 4.4588113 4.47892   4.4761305 4.587005

[[4.390997  4.407791  4.4315267 4.457498  4.4378104 4.5439067 4.495088
  4.690859 ]]
[[4.39101   4.407792  4.431528  4.457518  4.437811  4.543905  4.495086
  4.6908607]]
[[4.391013  4.4077973 4.4315333 4.4575295 4.4378138 4.5439067 4.495088
  4.6908655]]
[[4.391027  4.4078    4.431538  4.457548  4.4378176 4.5439067 4.4950905
  4.6908703]]
[[4.3910394 4.4078064 4.4315424 4.457569  4.437821  4.5439076 4.495094
  4.690873 ]]
[[4.3910336 4.4078045 4.4315453 4.4575567 4.4378223 4.5439095 4.4950943
  4.690875 ]]
[[4.3910336 4.4078054 4.431547  4.45755   4.437825  4.5439124 4.495097
  4.690875 ]]
[[4.3910213 4.4078007 4.431545  4.457533  4.4378223 4.5439115 4.4950943
  4.690873 ]]
[[4.3910136 4.4077997 4.4315405 4.457523  4.4378204 4.543911  4.495094
  4.6908693]]
[[4.3910203 4.407798  4.4315405 4.4575343 4.4378176 4.5439076 4.49509
  4.6908684]]
[[4.3910284 4.407803  4.4315457 4.4575486 4.437822  4.5439105 4.495094
  4.690872 ]]
[[4.3910346 4.4078026 4.431545  4.4575605 4.4378204 4.5439076 4

[[4.391128  4.4078546 4.4316287 4.4576716 4.4378824 4.543944  4.49514
  4.69094  ]]
[[4.3911366 4.407859  4.4316306 4.457686  4.4378843 4.5439444 4.4951425
  4.6909437]]
[[4.391132  4.407859  4.431632  4.4576735 4.437886  4.543946  4.4951444
  4.6909437]]
[[4.391128  4.4078584 4.4316344 4.4576645 4.4378867 4.543948  4.4951463
  4.6909447]]
[[4.3911195 4.407858  4.431634  4.4576526 4.4378867 4.5439496 4.495146
  4.690942 ]]
[[4.3911157 4.407853  4.431632  4.457638  4.4378853 4.543949  4.495144
  4.69094  ]]
[[4.3911195 4.407853  4.43163   4.4576507 4.4378824 4.543946  4.4951415
  4.690939 ]]
[[4.3911223 4.407852  4.431628  4.4576583 4.4378815 4.543944  4.4951396
  4.690939 ]]
[[4.391128  4.4078546 4.4316287 4.4576716 4.4378824 4.543944  4.49514
  4.69094  ]]
[[4.3911366 4.407859  4.4316306 4.457686  4.4378843 4.5439444 4.4951425
  4.6909437]]
[[4.391132  4.407859  4.431632  4.4576735 4.437886  4.543946  4.4951444
  4.6909437]]
[[4.391128  4.4078584 4.4316344 4.4576645 4.4378867 4.543948